// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ExecuteQuery(arg1:string):Promise<main.QueryResult>;

export function OpenDatabase():Promise<string>;

export function StreamQuery(arg1:string):Promise<void>;
