// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {sqliter} from '../models';

export function ListFiles(arg1:string):Promise<Array<sqliter.FileEntry>>;

export function ListTables(arg1:string):Promise<Array<sqliter.TableInfo>>;

export function OpenDatabase():Promise<string>;

export function Query(arg1:sqliter.QueryOptions):Promise<sqliter.QueryResult>;
