// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ExecuteQuery(arg1) {
  return window['go']['main']['App']['ExecuteQuery'](arg1);
}

export function OpenDatabase() {
  return window['go']['main']['App']['OpenDatabase']();
}

export function StreamQuery(arg1) {
  return window['go']['main']['App']['StreamQuery'](arg1);
}
